baseURL = "http://localhost:1313/"
languageCode = "en-us"
paginate = 5 #frontpage pagination
title = "Orange"
disqusShortname = "localblog-2"

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[menu]

  [[menu.main]]
    identifier = "features"
    name = "Features"
    url = "/#features"
    weight = -130

  [[menu.main]]
    name = "Screenshots"
    url = "/screenshots/"
    weight = -120

  [[menu.main]]
    identifier = "download"
    name = "Download"
    url = "/download/"
    weight = -110

  [[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = -100

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = -90




