baseURL = ""
languageCode = "en-us"
paginate = 10 #frontpage pagination
title = "Orange"
disqusShortname = "orange-4"
disablePathToLower = "True"
disableKinds = ["taxonomyTerm"] #workflows and blog landing pages do not generate correctly without this because of the custom list.html pages

[params]
  version = "3.35.0"

[markup.goldmark.renderer]
unsafe = true

[outputFormats]
  [outputFormats.workflow]
    mediaType = "application/json"
    baseName = "workflow"
  [outputFormats.blog]
    mediaType = "application/json"
    baseName = "blog"
   [outputFormats.searchindex]
       mediaType = "application/json"
       baseName = "search"

[outputs]
  home = [ "HTML", "workflow", "blog", "searchindex" ]
  section = [ "HTML", "json" ]

[taxonomies]
  workflow = "workflows"
  blog = "blog"

[menu]

  [[menu.main]]
    name = "Screenshots"
    url = "/screenshots/"
    weight = -120

  [[menu.main]]
    identifier = "workflows"
    name = "Workflows"
    url = "/workflows/"
    weight = -110

  [[menu.main]]
    identifier = "download"
    name = "Download"
    url = "/download/"
    weight = -100

  [[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = -90

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = -90

  [[menu.main]]
    name = "Workshops"
    url = "/training/"
    weight = -80

  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = -70

  [[menu.main]]
    name = "Donate"
    url = "https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=A76TAX87ZVR3J"
    weight = -60
